<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','max_length[255]|required');
		$this->form_validation->set_rules('name','Name','max_length[255]|required');
		$this->form_validation->set_rules('lastname','Lastname','max_length[255]|required');
		$this->form_validation->set_rules('username','Username','max_length[255]|required');
		$this->form_validation->set_rules('email','Email','max_length[255]|valid_email');
		$this->form_validation->set_rules('picture','Picture','max_length[255]');
		$this->form_validation->set_rules('profile_id','Profile Id','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'profile_id' => $this->input->post('profile_id'),
				'password' => $this->input->post('password'),
				'name' => $this->input->post('name'),
				'lastname' => $this->input->post('lastname'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'picture' => $this->input->post('picture'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
			$this->load->model('Profile_model');
			$data['all_profiles'] = $this->Profile_model->get_all_profiles();
            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($id_user)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id_user);
        
        if(isset($data['user']['id_user']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','max_length[255]|required');
			$this->form_validation->set_rules('name','Name','max_length[255]|required');
			$this->form_validation->set_rules('lastname','Lastname','max_length[255]|required');
			$this->form_validation->set_rules('username','Username','max_length[255]|required');
			$this->form_validation->set_rules('email','Email','max_length[255]|valid_email');
			$this->form_validation->set_rules('picture','Picture','max_length[255]');
			$this->form_validation->set_rules('profile_id','Profile Id','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'profile_id' => $this->input->post('profile_id'),
					'password' => $this->input->post('password'),
					'name' => $this->input->post('name'),
					'lastname' => $this->input->post('lastname'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'picture' => $this->input->post('picture'),
                );

                $this->User_model->update_user($id_user,$params);            
                redirect('user/index');
            }
            else
            {
				$this->load->model('Profile_model');
				$data['all_profiles'] = $this->Profile_model->get_all_profiles();

                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id_user)
    {
        $user = $this->User_model->get_user($id_user);

        // check if the user exists before trying to delete it
        if(isset($user['id_user']))
        {
            $this->User_model->delete_user($id_user);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
