<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Class_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get class by id_class
     */
    function get_class($id_class)
    {
        return $this->db->get_where('classes',array('id_class'=>$id_class))->row_array();
    }
        
    /*
     * Get all classes
     */
    function get_all_classes()
    {
        $this->db->order_by('id_class', 'desc');
        return $this->db->get('classes')->result_array();
    }
        
    /*
     * function to add new class
     */
    function add_class($params)
    {
        $this->db->insert('classes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update class
     */
    function update_class($id_class,$params)
    {
        $this->db->where('id_class',$id_class);
        return $this->db->update('classes',$params);
    }
    
    /*
     * function to delete class
     */
    function delete_class($id_class)
    {
        return $this->db->delete('classes',array('id_class'=>$id_class));
    }
}
