<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course by id_course
     */
    function get_course($id_course)
    {
        return $this->db->get_where('courses',array('id_course'=>$id_course))->row_array();
    }
        
    /*
     * Get all courses
     */
    function get_all_courses()
    {
        $this->db->order_by('id_course', 'desc');
        return $this->db->get('courses')->result_array();
    }
        
    /*
     * function to add new course
     */
    function add_course($params)
    {
        $this->db->insert('courses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course
     */
    function update_course($id_course,$params)
    {
        $this->db->where('id_course',$id_course);
        return $this->db->update('courses',$params);
    }
    
    /*
     * function to delete course
     */
    function delete_course($id_course)
    {
        return $this->db->delete('courses',array('id_course'=>$id_course));
    }
}
