<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Permision_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get permision by id_permission
     */
    function get_permision($id_permission)
    {
        return $this->db->get_where('permisions',array('id_permission'=>$id_permission))->row_array();
    }
        
    /*
     * Get all permisions
     */
    function get_all_permisions()
    {
        $this->db->order_by('id_permission', 'desc');
        return $this->db->get('permisions')->result_array();
    }
        
    /*
     * function to add new permision
     */
    function add_permision($params)
    {
        $this->db->insert('permisions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update permision
     */
    function update_permision($id_permission,$params)
    {
        $this->db->where('id_permission',$id_permission);
        return $this->db->update('permisions',$params);
    }
    
    /*
     * function to delete permision
     */
    function delete_permision($id_permission)
    {
        return $this->db->delete('permisions',array('id_permission'=>$id_permission));
    }
}
