<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_model');
    } 

    /*
     * Listing of courses
     */
    function index()
    {
        $data['courses'] = $this->Course_model->get_all_courses();
        
        $data['_view'] = 'course/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new course
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','max_length[255]|required');
		$this->form_validation->set_rules('code','Code','max_length[255]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'code' => $this->input->post('code'),
				'directory' => $this->input->post('directory'),
				'date_created' => $this->input->post('date_created'),
            );
            
            $course_id = $this->Course_model->add_course($params);
            redirect('course/index');
        }
        else
        {            
            $data['_view'] = 'course/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a course
     */
    function edit($id_course)
    {   
        // check if the course exists before trying to edit it
        $data['course'] = $this->Course_model->get_course($id_course);
        
        if(isset($data['course']['id_course']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','max_length[255]|required');
			$this->form_validation->set_rules('code','Code','max_length[255]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'code' => $this->input->post('code'),
					'directory' => $this->input->post('directory'),
					'date_created' => $this->input->post('date_created'),
                );

                $this->Course_model->update_course($id_course,$params);            
                redirect('course/index');
            }
            else
            {
                $data['_view'] = 'course/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The course you are trying to edit does not exist.');
    } 

    /*
     * Deleting course
     */
    function remove($id_course)
    {
        $course = $this->Course_model->get_course($id_course);

        // check if the course exists before trying to delete it
        if(isset($course['id_course']))
        {
            $this->Course_model->delete_course($id_course);
            redirect('course/index');
        }
        else
            show_error('The course you are trying to delete does not exist.');
    }
    
}
